<?php

add_filter('acf/settings/show_admin', '__return_false');


			if( function_exists('acf_add_local_field_group') ):

acf_add_local_field_group(array(
	'key' => 'group_6236f6b0f1d01',
	'title' => 'Page Footer',
	'fields' => array(
		array(
			'key' => 'field_6236f6b58caa7',
			'label' => 'Footer',
			'name' => 'footer',
			'type' => 'button_group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'show' => 'Show',
				'hide' => 'Hide',
			),
			'allow_null' => 0,
			'default_value' => 'show',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

acf_add_local_field_group(array(
	'key' => 'group_62039f1c91ffa',
	'title' => 'Project Details',
	'fields' => array(
		array(
			'key' => 'field_62039f2026621',
			'label' => 'Summary',
			'name' => 'summary',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Enter project summary here...',
			'maxlength' => '',
			'rows' => 4,
			'new_lines' => '',
		),
		array(
			'key' => 'field_62399fe605038',
			'label' => 'Excerpt',
			'name' => 'excerpt',
			'type' => 'textarea',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Enter project summary here...',
			'maxlength' => '',
			'rows' => 4,
			'new_lines' => '',
		),
		array(
			'key' => 'field_62039f4226622',
			'label' => 'Client',
			'name' => 'client',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Project client..',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_62039f5026623',
			'label' => 'Year',
			'name' => 'year',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Project year..',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'portfolio',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

acf_add_local_field_group(array(
	'key' => 'group_6203962596423',
	'title' => 'Page Header',
	'fields' => array(
		array(
			'key' => 'field_6203962d17455',
			'label' => 'Page Header',
			'name' => 'page_header',
			'type' => 'select',
			'instructions' => 'Select page header for this page.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'global' => 'Use Global',
				'show' => 'Show',
				'hide' => 'Hide',
			),
			'default_value' => 'global',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_62039a1a5f562',
			'label' => 'Page Title',
			'name' => 'page_title',
			'type' => 'text',
			'instructions' => 'Leave it empty if you want to display page\'s original title.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Enter page title..',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_62039b33e9b1e',
			'label' => 'Animate Title',
			'name' => 'animate_title',
			'type' => 'select',
			'instructions' => 'Swtich "no" if you don\'t want to animate page title.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'global' => 'Use Global',
				'true' => 'Yes',
				'false' => 'No',
			),
			'default_value' => 'global',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_62039b78e9b1f',
			'label' => 'Header Background',
			'name' => 'header_background',
			'type' => 'color_picker',
			'instructions' => 'Leave it empty if you want to use global background color.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'enable_opacity' => 0,
			'return_format' => 'array',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'page',
			),
		),
	),
	'menu_order' => 1,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'show_in_rest' => 0,
));

acf_add_local_field_group(array(
	'key' => 'group_62039da0df2c2',
	'title' => 'Project Header',
	'fields' => array(
		array(
			'key' => 'field_62039db3a3dd9',
			'label' => 'Header Style',
			'name' => 'header_style',
			'type' => 'select',
			'instructions' => 'Select project header style.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'global' => 'Use Global',
				'style_1' => 'Half Image',
				'style_2' => 'Full Image',
				'style_3' => 'No Image',
				'no_header' => 'No Header',
			),
			'default_value' => 'global',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_62039ef1a3bd8',
			'label' => 'Animate Header',
			'name' => 'animate_header',
			'type' => 'button_group',
			'instructions' => 'Switch "Yes" if you want to animate header.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'true' => 'Yes',
				'false' => 'No',
			),
			'allow_null' => 0,
			'default_value' => 'true',
			'layout' => 'horizontal',
			'return_format' => 'value',
		),
		array(
			'key' => 'field_6203a8b1639aa',
			'label' => 'Featured Image Type',
			'name' => 'featured_image_type',
			'type' => 'select',
			'instructions' => 'Select header featured image type.',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'image' => 'Image',
				'video' => 'Video',
			),
			'default_value' => 'image',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_6203a8d8639ab',
			'label' => 'Video ID',
			'name' => 'video_id',
			'type' => 'text',
			'instructions' => 'Enter your video id here.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6203a8b1639aa',
						'operator' => '==',
						'value' => 'video',
					),
					array(
						'field' => 'field_6203a924639ac',
						'operator' => '!=',
						'value' => 'self_hosted',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => 'Eg. 631871963',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_6203a924639ac',
			'label' => 'Video Source',
			'name' => 'video_provider',
			'type' => 'select',
			'instructions' => 'Select embed video provider here.',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6203a8b1639aa',
						'operator' => '==',
						'value' => 'video',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'vimeo' => 'Vimeo',
				'youtube' => 'YouTube',
				'self_hosted' => 'Self Hosted',
			),
			'default_value' => 'vimeo',
			'allow_null' => 0,
			'multiple' => 0,
			'ui' => 0,
			'return_format' => 'value',
			'ajax' => 0,
			'placeholder' => '',
		),
		array(
			'key' => 'field_624721ab93efa',
			'label' => 'Upload Video',
			'name' => 'upload_video',
			'type' => 'file',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_6203a924639ac',
						'operator' => '==',
						'value' => 'self_hosted',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'url',
			'library' => 'all',
			'min_size' => '',
			'max_size' => '',
			'mime_types' => '',
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'post_type',
				'operator' => '==',
				'value' => 'portfolio',
			),
		),
	),
	'menu_order' => 10,
	'position' => 'side',
	'style' => 'default',
	'label_placement' => 'left',
	'instruction_placement' => 'field',
	'hide_on_screen' => '',
	'active' => true,
	'description' => 'Customize project header here.',
	'show_in_rest' => 0,
));

endif;		